#言語：python3
#問題URL：https://paiza.jp/works/mondai/stdin_primer/stdin_primer__integer_space_boss
https://paiza.jp/works/mondai/stdin_primer/stdin_primer__integer_space_step4
https://paiza.jp/works/mondai/stdin_primer/stdin_primer__integer_space_step3
https://paiza.jp/works/mondai/stdin_primer/stdin_primer__integer_space_step2
#コメント：
#コード：
#```py
a=input().split()
print(*a,sep="\n")
#```